version: 2

jobs:
   build-linux-x86_64:
     docker:
       - image: eaplatanios/tensorflow_scala:linux-cpu-x86_64-0.6.0
     working_directory: ~/repository
     environment:
       LD_LIBRARY_PATH: /usr/lib:$LD_LIBRARY_PATH
       JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
       JVM_OPTS: -Xmx3200m
       TERM: dumb
     steps:
       - checkout
       - run: mkdir downloads && cd downloads
       - run: wget https://oss.sonatype.org/service/local/repositories/snapshots/content/org/platanios/tensorflow_2.13/0.6.0-SNAPSHOT/tensorflow_2.13-0.6.0-SNAPSHOT-linux.jar
       - run: jar xf tensorflow_2.13-0.6.0-SNAPSHOT-linux.jar
       - run: mv libtensorflow.so /usr/lib/libtensorflow.so
       - run: mv libtensorflow_framework.so /usr/lib/libtensorflow_framework.so
       - run: ln -s /usr/lib/libtensorflow.so /usr/lib/libtensorflow.so.2
       - run: ln -s /usr/lib/libtensorflow.so /usr/lib/libtensorflow.so.2.4.0
       - run: ln -s /usr/lib/libtensorflow_framework.so /usr/lib/libtensorflow_framework.so.2
       - run: ln -s /usr/lib/libtensorflow_framework.so /usr/lib/libtensorflow_framework.so.2.4.0
       - run: cd ..
       - restore_cache:
           keys:
             - v0.5.1-dependencies-{{ checksum "build.sbt" }}
       - run: cat /dev/null | sbt +test:compile
       - save_cache:
           paths:
             - ~/.ivy2
           key: v0.5.1-dependencies--{{ checksum "build.sbt" }}
       - run: cat /dev/null | sbt +test:test

workflows:
  version: 2
  test:
    jobs:
      - build-linux-x86_64
